# Generated by Django 4.1.7 on 2023-03-02 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(default='NullPlatformName', max_length=30)),
                ('Data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(default='NoUserName', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Videojoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(default='NullGameName', max_length=30)),
                ('Preu', models.IntegerField(default=0)),
                ('Nou', models.BooleanField(default=True)),
                ('Plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnchainedApp.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='usuari_videojoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UnchainedApp.usuari')),
                ('Videojoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UnchainedApp.videojoc')),
            ],
        ),
        migrations.CreateModel(
            name='usuari_plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plataforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UnchainedApp.plataforma')),
                ('Usuari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UnchainedApp.usuari')),
            ],
        ),
        migrations.AddField(
            model_name='usuari',
            name='Plataforma',
            field=models.ManyToManyField(through='UnchainedApp.usuari_plataforma', to='UnchainedApp.plataforma'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='Videojoc',
            field=models.ManyToManyField(through='UnchainedApp.usuari_videojoc', to='UnchainedApp.videojoc'),
        ),
    ]
